apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-pipeline
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
data:
  logstash.conf: |
    input {
      beats {
        port => {{ .Values.beatsPort }}
      }
    }
    output {

      stdout {}

      newrelic {
        license_key => "{{ .Values.newRelicLicenseKey }}"
        base_uri => "{{ .Values.newRelicLogsApi }}"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
data:
  logstash.yml: |
    http.host: "0.0.0.0"